@host = http://localhost:3000

###
GET {{host}}/

###
POST {{host}}/

###
GET {{host}}/ping

###
GET {{host}}/kingkong/king

###
GET {{host}}/greet/rainer

###
GET {{host}}/greet?salutation=Hi&name=rainer

###
GET {{host}}/greet?salutation=Hi

###
GET {{host}}/greet?name=rainer

###
GET {{host}}/greet

###
POST {{host}}/greet
Content-Type: application/json

{
    "salutation": "Hi",
    "name": "rainer"
}

###
GET {{host}}/lookup/8

###
GET {{host}}/random

###
GET {{host}}/numbers

###
POST {{host}}/numbers
Content-Type: application/json

1

###
GET {{host}}/poem
