@host = http://localhost:8080

###
GET {{host}}/ping
Accept: text/html

###
GET {{host}}/level2

###
POST {{host}}/level2?foo=bar
Content-Type: application/json

{
    "foo": "Bar"
}

###
POST {{host}}/level3/file?foo=bar
Content-Type: application/json

{
    "foo": "Bar"
}

###
GET {{host}}/level3?foo=bar

###
GET {{host}}/level4
