GET http://localhost:3000/level2

###
POST http://localhost:3000/level2?foo=bar
Content-Type: application/json

{
    "foo": "Bar"
}

###
POST http://localhost:3000/level3/file?foo=bar
Content-Type: application/json

{
    "foo": "Bar"
}

###
GET http://localhost:3000/level3?foo=bar

###
GET http://localhost:3000/level4
