cfdev:
	cd word_puzzle_cloudflare; npm run dev

spin:
	cd word_puzzle_spin; spin build; spin up

cf-deploy:
	cd word_puzzle_cloudflare; npm run deploy

spin-deploy:
	cd word_puzzle_spin; spin build; spin deploy
